server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.198.130:8848
    sentinel:
      transport:
        dashboard: 192.168.198.130:8080
        port: 8719


#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true